# Generated by Django 5.1.3 on 2025-07-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="comments",
            field=models.TextField(blank=True),
        ),
    ]
