# Generated by Django 5.1.3 on 2025-10-16 10:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_alter_product_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("48", "48"),
                            ("49", "49"),
                            ("50", "50"),
                            ("51", "51"),
                            ("52", "52"),
                            ("53", "53"),
                            ("54", "54"),
                            ("55", "55"),
                            ("56", "56"),
                            ("57", "57"),
                            ("58", "58"),
                            ("59", "59"),
                            ("60", "60"),
                            ("61", "61"),
                            ("62", "62"),
                            ("63", "63"),
                            ("64", "64"),
                            ("65", "65"),
                            ("66", "66"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sku",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
            ],
            options={
                "ordering": ["product_id", "size"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_user_cartitem",
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_session_cartitem",
        ),
        migrations.AlterField(
            model_name="product",
            name="serial_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[django.core.validators.RegexValidator("^[\\w\\-\\.]+$")],
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="ecommerce.product",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecommerce.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecommerce.productvariant",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False), ("variant__isnull", False)),
                fields=("user", "product", "variant"),
                name="unique_user_product_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False), ("variant__isnull", True)),
                fields=("user", "product"),
                name="unique_user_product_no_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("session_key__isnull", False), ("variant__isnull", False)
                ),
                fields=("session_key", "product", "variant"),
                name="unique_session_product_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("session_key__isnull", False), ("variant__isnull", True)
                ),
                fields=("session_key", "product"),
                name="unique_session_product_no_variant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "size")},
        ),
    ]
