# Generated by Django 5.1.3 on 2025-07-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_remove_product_comments_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="serial_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
