# Generated by Django 5.1.3 on 2025-10-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerce",
            "0003_productvariant_remove_cartitem_unique_user_cartitem_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
