# Generated by Django 5.1.3 on 2025-10-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
