# Generated by Django 5.1.3 on 2025-10-21 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0005_order_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBundleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=120)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundled_as_item",
                        to="ecommerce.product",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundle_links",
                        to="ecommerce.product",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="bundle_items",
            field=models.ManyToManyField(
                blank=True,
                related_name="bundled_with",
                through="ecommerce.ProductBundleItem",
                to="ecommerce.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="productbundleitem",
            constraint=models.UniqueConstraint(
                fields=("product", "item"), name="uniq_product_item_bundle"
            ),
        ),
    ]
