# Generated by Django 5.2.7 on 2025-11-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0006_productbundleitem_product_bundle_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_checkout_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
