# Generated by Django 5.2.7 on 2025-12-03 14:07

import django.db.models.deletion
from django.db import migrations, models, connection


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0007_add_stripe_checkout_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ["-added_at"],
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="coupon",
            options={
                "ordering": ["code"],
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
            },
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-id"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={
                "ordering": ["product_id", "size"],
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
            },
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={
                "ordering": ["-id"],
                "verbose_name": "Rating",
                "verbose_name_plural": "Ratings",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="All categories this product belongs to (including Sale)",
                related_name="categorized_products",
                to="ecommerce.category",
            ),
        ),
        migrations.RunPython(
            # Populate categories field with primary category for existing products
            lambda apps, schema_editor: [
                p.categories.add(p.category) 
                for p in apps.get_model('ecommerce', 'Product').objects.select_related('category').all()
                if p.category and p.category not in p.categories.all()
            ],
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Primary category (for backward compatibility)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="ecommerce.category",
            ),
        ),
    ]
