# Generated by Django 5.1.3 on 2025-07-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerce",
            "0007_order_address_order_city_order_full_name_order_phone_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.TextField(default="N/A"),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="full_name",
            field=models.CharField(default="Anonymous", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(default="N/A", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="postal_code",
            field=models.CharField(default="0000", max_length=20),
        ),
    ]
