# Generated by Django 5.2.7 on 2025-12-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0008_add_categories_manytomany"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the product should be automatically removed from Sale category. Leave empty if no expiration.",
                null=True,
            ),
        ),
    ]
