# Generated by Django 5.1.3 on 2025-07-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0009_alter_order_address_alter_order_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cart_add_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
