# Generated by Django 5.2.7 on 2025-12-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0011_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Featured image for blog post",
                null=True,
                upload_to="blog/",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Optional video URL (YouTube, Vimeo, etc.)",
                null=True,
            ),
        ),
    ]
