# Generated by Django 5.2.7 on 2025-12-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0012_blogpost_image_blogpost_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a video file (MP4, WebM, OGG). Max size: 100MB",
                null=True,
                upload_to="blog/videos/",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Optional video URL (YouTube, Vimeo, etc.) or upload a file above",
                null=True,
            ),
        ),
    ]
