# Generated by Django 5.1.3 on 2025-07-27 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0013_shippingoption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="paid",
        ),
        migrations.RemoveField(
            model_name="order",
            name="stripe_payment_intent",
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecommerce.shippingoption",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=255),
        ),
    ]
