# Generated by Django 5.1.3 on 2025-07-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerce",
            "0014_remove_order_paid_remove_order_stripe_payment_intent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
