# Generated by Django 5.2.7 on 2026-01-04 19:46

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs_for_existing_products(apps, schema_editor):
    """Generate slugs for all existing products."""
    Product = apps.get_model('ecommerce', 'Product')
    # Only select fields that exist in the database at this migration point
    for product in Product.objects.only('id', 'name', 'slug').all():
        if not product.slug:
            base_slug = slugify(product.name) or f"product-{product.pk}"
            slug = base_slug
            counter = 1
            # Ensure uniqueness
            while Product.objects.filter(slug=slug).exclude(pk=product.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            Product.objects.filter(pk=product.pk).update(slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0016_bannerimage"),
    ]

    operations = [
        # Step 1: Add field as nullable and non-unique
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                null=True,
                help_text="URL-friendly version of product name",
                max_length=250,
            ),
        ),
        # Step 2: Generate slugs for existing products
        migrations.RunPython(generate_slugs_for_existing_products, migrations.RunPython.noop),
        # Step 3: Make field non-nullable and unique
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of product name",
                max_length=250,
                unique=True,
            ),
        ),
    ]
