# Generated by Django 5.2.7 on 2026-01-04 19:46

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs_for_existing_products(apps, schema_editor):
    """Generate slugs for all existing products."""
    Product = apps.get_model('ecommerce', 'Product')
    for product in Product.objects.all():
        if not product.slug:
            base_slug = slugify(product.name)
            slug = base_slug
            counter = 1
            # Ensure uniqueness
            while Product.objects.filter(slug=slug).exclude(pk=product.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            product.slug = slug
            product.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0016_bannerimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of product name",
                max_length=250,
                unique=True,
            ),
        ),
        migrations.RunPython(generate_slugs_for_existing_products, migrations.RunPython.noop),
    ]
